site:
    title: "【催泪、小丑】的博客"
    subtitle: "每天给自己一个希望，试着不为明天而烦恼，不为昨天而叹息，只为今天更美好。"
    limit: 10
    theme: theme
    lang: zh-cn
    url: "https://blog.longkui.top/"
    comment: username
    logo: "-/images/avatar_long.jpg"
    config:
        CustomVar: "config 下是纸小墨的自定义变量，定义时建议使用正确大小写"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # link: "{year}{month}{day}{hour}{minute}{second}.html"
    # root: "/blog"

authors:
    me:
        name: "【催泪、小丑】"
        intro: "每天给自己一个希望，试着不为明天而烦恼，不为昨天而叹息，只为今天更美好。"
        avatar: "-/images/avatar_long.jpg"

build:
    # output: "public"
    port: 18000
    # These files are copied to the public folder when 'ink build' is used
    copy:
        - "source/images"
    # Executed commands when 'ink publish' is used
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
